name: Build LaTeX and deploy on GitHub Releases
on:
  push:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  Build-LaTeX:
    runs-on: ubuntu-22.04
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Install TeXLive
        uses: DanySK/setup-texlive-action@master
      - name: Compile LaTeX
        uses: DanySK/compile-latex-action@master
      - name: Autotag
        uses: DanySK/semver-autotag-action@master
      - name: Deploy
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git describe --tags --exact-match HEAD)
          hub release create -m "$(git tag -l --format='%(contents)' "$TAG")" "$TAG" || true
          while IFS= read -r file; do
            pdf="${file%.*}.pdf"
            echo "Delivering file $pdf"
            gh release upload "$TAG" "$pdf" --clobber
          done <"success-list"
