package it.unibo.apice.oop.p14io.others;
public class Persona implements java.io.Serializable{
	
	// Generated by Eclipse
	private static final long serialVersionUID = -8985026380526620812L;
	
	final private String nome;
    final private int annoNascita;
    final private boolean sposato;
  
    public Persona(String nome,int annoNascita,boolean sposato){
    	this.nome = nome;		
    	this.annoNascita = annoNascita;
    	this.sposato = sposato;
    }
  
    public String toString(){
    	return this.nome + ":" + this.annoNascita + ":" + 
    	       (this.sposato ? "spos" : "non-spos");
    }
}